name: Create Production Builds

on:
  push:
    branches: ["main"]

jobs:
  build_android:
    type: build # This job type creates a production build for Android
    params:
      platform: android
  submit_android:
    name: Submit to Google Play Store
    needs: [build_android]
    type: submit
    params:
      platform: android
      build_id: ${{ needs.build_android.outputs.build_id }}
  build_ios:
    type: build # This job type creates a production build for iOS
    params:
      platform: ios
  submit_ios:
    name: Submit to App Store
    needs: [build_ios]
    type: submit
    params:
      platform: ios
      build_id: ${{ needs.build_ios.outputs.build_id }}
